name: 24/7 MAX SPEED

on:
  schedule:
    - cron: '0 */6 * * *' # Startet alle 6 Stunden automatisch neu
  workflow_dispatch:      # Ermöglicht den manuellen Start per Button

jobs:
  snipe:
    runs-on: ubuntu-latest
    concurrency:
      group: vinted-sniper
      cancel-in-progress: true # Verhindert, dass der Bot doppelt läuft
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager discord-webhook

      - name: Run Sniper
        run: python sniper.py
