name: Vinted Sniper

concurrency:
  group: sniper-vinted-group
  cancel-in-progress: true 

on:
  workflow_dispatch:      
  schedule:
    - cron: '*/15 * * * *' 

jobs:
  snipe:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: System Cleanup
        run: |
          sudo pkill -9 chrome || true
          sudo pkill -9 chromedriver || true
          rm -rf /home/runner/.wdm/

      - name: Install Dependencies
        run: |
          pip install selenium==4.15.2 webdriver-manager discord-webhook

      - name: Run Sniper
        run: python sniper.py
