name: 24/7 MAX SPEED

on:
  schedule:
    - cron: '0 */6 * * *' # Startet alle 6 Stunden neu (sauberer Turnus)
  workflow_dispatch: # Erlaubt manuellen Start

jobs:
  snipe:
    runs-on: ubuntu-latest
    concurrency: 
      group: vinted-sniper
      cancel-in-progress: true # WICHTIG: Beendet den alten Prozess, wenn ein neuer startet
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager discord-webhook
      - name: Run Sniper
        run: python sniper.py
